on: [push]

jobs:
  dependency_analysis:
    runs-on:  ubuntu-latest
    name: Test dependencies for security flaws
    steps:
      - uses: actions/checkout@v3
      - name: Dependency Check
        run: pip3 install safety && safety check
        shell: bash
