name: Semgrep

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  code_analysis:
    runs-on:  ubuntu-latest
    name: Analyse code for security flaws
    steps:
      - uses: actions/checkout@v2
      - name: Code Security Analysis
        run: docker run --rm -e SEMGREP_RULES='p/default' -e SEMGREP_BASELINE_REF='${GIT_BRANCH}' -e SEMGREP_TIMEOUT='300' returntocorp/semgrep semgrep ci --config auto
        shell: bash
